### ISSUE TITLE
Brainslag

### ISSUE THREAD

**Issue by sanchezquibus** [pierky/ripe-atlas-monitor#3] opened 2016-05-23 16:44 UTC
Hello,
I'm not a good programmer even so I'm trying to install the ripe-atlas-monitor in my CPU, due to I need to create a new monitor for myself. I'm following the several steps to get it, but at then end, when I try to monitor a measurement id, it appears a heads up saying: "No handlers could be found for logger "RIPEAtlasMonitor"". I was searching how to solve that but I didn't find it. Could you help me out? I'm hopeless.
Regardless, thanks in advance.

**Comment by pierky** [comment] 2016-05-23 17:11
Hello,

does the program print any error stack trace?
Can you post your configuration file's content and monitor's configutation (if so, please remove any sensitive data)?

**Comment by sanchezquibus** [comment] 2016-05-24 14:34
Hi,
yes sorry, when I said heads up I meant one error stack trace!
I send you 2 image attached as you asked for it.
Thx in advance.

![captura de 2016-05-24 16 28 06](https://cloud.githubusercontent.com/assets/17910620/15507809/598f79f8-21cd-11e6-973a-b2cfc6e9fb02.png)
![config](https://cloud.githubusercontent.com/assets/17910620/15507810/5993dea8-21cd-11e6-9582-20f9e657cc27.png)

**Comment by pierky** [comment] 2016-05-24 16:25
Ok, thanks. Unfortunately that's not enough for me to understand where the problem is.

Currently I can only suggest you to verify that the global configuration file is in a valid YAML format and that it can be read by the program, and also that the **var** directory contains the **status**, **locks** and **monitors** subdirs and that they can be written by the current user who executes the program.

To have a better view of the issue I have to ask you to make a little change in the code of the program, by editing the **ripe-atlas-monitor** script that is within your virtual-env: on the basis of your screenshots I guess it should be at `~/Envs/venv/bin/ripe-atlas-monitor`.

You should replace the last 8 lines of code with a single line:
- remove the following 8 lines:

```
try:
    sys.exit(main())
except RIPEAtlasMonitorError as e:
    logger.error(e)
    sys.exit(1)
except Exception as e:
    logger.error(e, exc_info=True)
    sys.exit(1)
```
- add the following line:

```
main()
```

Finally, please run the command again and send me the output.

For the future, I'll plan to add an environmental variable that can be set in order to skip this lines of code in case of debug.

Thanks for your contribution.

**Comment by pierky** [comment] 2016-07-06 17:19
Tentatively closing this with 8d5344c4da89d298364245e57ac4b6f5a50cb0d3 (v0.1.9)

**Closed as completed by pierky** 2016-07-06 17:19 UTC
